version: "3.9"

services:
  gateway:
    build:
      context: ..
      dockerfile: deploy/gateway/Dockerfile
    container_name: gateway
    ports:
      - "5000:8080" # host:container
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      FILE_STORING_BASE_URL: "http://file-storing-service:8080"
      FILE_ANALYSIS_BASE_URL: "http://file-analysis-service:8080"
    depends_on:
      - file-storing-service
      - file-analysis-service

  file-storing-service:
    build:
      context: ..
      dockerfile: deploy/file-storing-service/Dockerfile
    container_name: file-storing-service
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      FILE_STORAGE_ROOT: "/app/storage"
    volumes:
      - files_data:/app/storage

  file-analysis-service:
    build:
      context: ..
      dockerfile: deploy/file-analysis-service/Dockerfile
    container_name: file-analysis-service
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      FILE_STORING_BASE_URL: "http://file-storing-service:8080"

  # Пример БД
  # db:
  #   image: postgres:16
  #   container_name: antiplag-db
  #   environment:
  #     POSTGRES_USER: antiplag
  #     POSTGRES_PASSWORD: antiplag
  #     POSTGRES_DB: antiplag
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data

volumes:
  files_data:
  # db_data:
